http:
 listener:
  host: "0.0.0.0"
  
 request:
  customerPath: "/api/customer"
  productPath: "/api/product"
  transactionPath: "/api/transaction"
  transactionReportPath: "/api/transactionReport"
  
